namespace:
  create: false
  name: microservices

prometheus:
  image: prom/prometheus:v2.54.1
  retention: 7d
  scrapeInterval: 15s
  evaluationInterval: 15s
  serviceAccountName: prometheus
  clusterIPServiceName: prometheus-clusterip
  loadBalancerServiceName: prometheus-loadbalancer
  namespaceLabel: microservices
  alertingTarget: alertmanager:9093
  alertJobName: kubernetes-endpoints
  alertRuleFor: 10s
  alertExpr: vector(1) == 1

alertmanager:
  image: prom/alertmanager:v0.28.0
  smtpPassword: changeme

grafana:
  image: grafana/grafana:11.4.0
  adminUser: admin
  adminPassword: admin

serviceMonitor:
  interval: 15s
